### ISSUE TITLE
Brightness keys as function keys

### ISSUE THREAD

**Issue by hugegreenbug** [GalliumOS/xfce4-power-manager#2]
Most chromebooks have media keys that show up as function keys. The power manager doesn't manage these keys as media keys.

We need to write a patch for the power manager respond to these function keys. Ideally, these keys should be configuration in case chromebooks use different F keys.

**Comment by coolstar** [comment]
I prefer the approach crouton went for this. They use xkbmap to map Super_L with the top row of keys to work as function keys.

https://www.reddit.com/r/chrubuntu/comments/1rsxkd/list_of_fixes_for_xubuntu_1310_on_the_acer_c720/ch74rb

This is similar to the approach we went for Windows on chromebook as well. On Windows we use AutoHotKey to map Ctrl + Top row of keys to the respective key. That way the F keys can still be used as F keys if needed.

**Comment by hugegreenbug** [comment]
That's cool. I think that should be a different issue. The issue here is
that the power manager only recognizes certain key codes for adjusting the
brightness.

Hugh

**Comment by james-reefer** [comment]
To piggyback off of CoolStar, I think that we should throw a simple toggle
dialog together (I volunteer). I use the function keys a lot in the
Monodevelop debugger, and I never use the media keys. Being able to switch
between modes would be a big feature in my eyes.

**Comment by hugegreenbug** [comment]
Sounds good. I think you would need to modify xfce4-settings:
https://github.com/GalliumOS/xfce4-settings. I've already made
modifications to it for the mouse. I was a bit sloppy and I didn't add my
changes as a patch in the package. I think that would be a good model to
follow for our changes so it would be easier to integrate in a new XFCE
release. I'm going to fix my changes so that are in patch form.

Hugh
